"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { useEffect } from "react";
import "@/pages/components/Layout/tailwindStyles";
import SidebarLayout from "@/pages/components/Layout/SidebarLayout";
import Providers from "./utils/providers";
import { ThemeProvider } from "@mui/material/styles";
import { baselightTheme } from "@/pages/utils/theme/DefaultColors";
import router, { useRouter } from "next/navigation";
import { User } from "./api/user";
const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: React.ReactNode;
  user: User; // User-Props hinzufügen
}

export default function RootLayout({ children, user }: RootLayoutProps) {
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      // Redirect to login, preserving the intended destination
      router.push(`/login?redirect=${router}`);
    }
  }, [user, router]);

  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={baselightTheme}>
          <SidebarLayout>{children}</SidebarLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
